#
# Pack nugets for consumption
#
jobs:
- job: nuget
  displayName: Release Nugets
  pool:
    name: Hosted Windows 2019 with VS2019
  steps:
  - script: |
      dotnet tool install --tool-path . GitVersion.Tool
      dotnet-gitversion /output buildserver
    displayName: Versioning
  - task: DownloadPipelineArtifacts@2
    inputs:
      artifact: 'release_$(GitVersion.FullSemVer)'
      path: $(Build.ArtifactStagingDirectory)
  - task: NuGetCommand@2
    displayName: 'NuGet Release Push'
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.snupkg'
      nuGetFeedType: external
      publishFeedCredentials: 'azureiiot-nuget'
      verbosityPush: Normal
    continueOnError: true
